Repository hms-dbmi/pic-sure-hpds, pull requests merged in 2023-10, with the labels that each got.

#85 [ALS-5053] pen test medium stacktrace error
  client-api/pom.xml
  docker/pic-sure-hpds/server.xml
  pom.xml
  war/pom.xml
  war/src/main/webapp/WEB-INF/web.xml
Labels: enhancement

#86 [ALS-5056] QueryRequest sumtype
  data/pom.xml
  data/src/main/java/edu/harvard/hms/dbmi/avillach/hpds/data/phenotype/ColumnMeta.java
  pom.xml
  service/pom.xml
  service/src/main/resources/jaxrs-context.xml
Labels: enhancement

#87 [ALS-5050] Ignore invalid concept paths in anyRecordOf queries
  processing/src/main/java/edu/harvard/hms/dbmi/avillach/hpds/processing/AbstractProcessor.java
  processing/src/test/java/edu/harvard/hms/dbmi/avillach/hpds/processing/AbstractProcessorTest.java
Labels: bug

#88 Release 0004
  client-api/pom.xml
  docker/pic-sure-hpds/server.xml
  pom.xml
  war/pom.xml
  war/src/main/webapp/WEB-INF/web.xml
Labels: ignore-for-release
