Repository hms-dbmi/pic-sure-hpds, pull requests merged in 2024-10, with the labels that each got.

#121 Remove lombok. Add record
  client-api/pom.xml
  data/pom.xml
  data/src/main/java/edu/harvard/hms/dbmi/avillach/hpds/data/genotype/InfoColumnMeta.java
  genomic-processor/pom.xml
  pom.xml
  processing/src/main/java/edu/harvard/hms/dbmi/avillach/hpds/processing/GenomicProcessorNodeImpl.java
  processing/src/test/java/edu/harvard/hms/dbmi/avillach/hpds/processing/genomic/GenomicProcessorRestClientTest.java
  service/src/main/java/edu/harvard/hms/dbmi/avillach/hpds/service/PicSureService.java
Labels: enhancement

#123 Fix bucket index loading for non-variant explorer environments
  processing/src/main/java/edu/harvard/hms/dbmi/avillach/hpds/processing/GenomicProcessorNodeImpl.java
  processing/src/main/java/edu/harvard/hms/dbmi/avillach/hpds/processing/VariantService.java
Labels: bug

#124 ALS-7635: Upgrade avro version
  .github/workflows/label-checker.yml
  pom.xml
Labels: dependencies

#125 Remove superfluous file load attempt
  processing/src/main/java/edu/harvard/hms/dbmi/avillach/hpds/processing/VariantService.java
Labels: bug
